---
- name: Clone or update gadget-pppd-units from bitbucket.
  include_role:
    name: cognifloyd.bitbucket-sources
    allow_duplicates: yes
    private: yes
    # with private, we can reuse the role, but we can't access registers
    # including: bitbucket_sources_return and bitbucket_sources_key_copy
  vars:
    bitbucket_sources_repo_type: "{{ gadget_pppd_clone_repo_type }}"
    bitbucket_sources_repo_account: "{{ gadget_pppd_clone_repo_account }}"
    bitbucket_sources_repo_name: "{{ gadget_pppd_clone_repo_name }}"
    bitbucket_sources_dest: "{{ gadget_pppd_clone_dest }}"
    bitbucket_sources_owner: "{{ gadget_pppd_clone_owner }}"
    bitbucket_sources_group: "{{ gadget_pppd_clone_group }}"
    bitbucket_sources_key: "{{ gadget_pppd_clone_key }}"
  tags:
    - deploy

- name: Include distro-specific vars (like package names)
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Include distro-specific package install tasks
  # RedHat-family installs custom rpms
  # Gentoo merely adds a patch in /etc/portage/patches
  # Ignoring other distros for now.
  include: "{{ item }}"
  with_first_found:
    # Be sure that any distro-packages.yml includes default-packages.yml
    - "{{ ansible_distribution }}-packages.yml"
    - "{{ ansible_os_family }}-packages.yml"
    - default-packages.yml

#- name: Check Kernel Requirements
  # Debian has ppp-modules, but it is only for debian-installer images.
  # Gentoo will require something extra to ensure kernel is compiled correctly.
  # RedHat seems to have necessary modules (just works with modules galore)

- name: Install tmpfiles.d file
  become: yes
  copy:
    remote_src: yes
    src: "{{ gadget_pppd_clone_dest }}/gadget-tmpfiles.conf"
    dest: "/usr/lib/tmpfiles.d/"
  notify:
    - systemd-tmpfiles --create

# Maybe this should go after the systemd unit installation
# That way it can't trigger until units are installed.
- name: Install udev rules
  become: yes
  template:
    src: "etc/udev/rules.d/72-gadget-ttyacm.rules.j2"
    dest: "/etc/udev/rules.d/72-{{ gadget_pppd_udev_rules_name }}-ttyacm.rules"

- name: Install common unit EnvironmentFile
  become: yes
  template:
    src: "etc/gadget-pppd.conf.j2"
    dest: "/etc/gadget-pppd.conf"

# TODO: This does not allow for modifying the IP* scheme.
# That will have to wait till #2 is done:
#   https://bitbucket.org/theatro-noc/gadget-pppd-units/issues/2/
- name: Install unit files
  include: install-unit-files.yml
  tags:
    - deploy

- name: Ensure dependent unit directory exists (gadget.target.wants)
  become: yes
  file:
    path: /etc/systemd/system/gadget.target.wants
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install dependent units
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/gadget.target.wants/{{ item | basename }}"
  with_items: "{{ gadget_pppd_dependent_units }}"
  when: gadget_pppd_dependent_units
  notify: gadget-pppd systemd daemon-reload
  tags:
    - deploy

