
- name: Copy custom RPMs
  copy:
    src: "{{ gadget_pppd_custom_rpm_dir_src }}/{{ item }}"
    dest: "{{ gadget_pppd_custom_rpm_dir }}"
  with_items: "{{ gadget_pppd_custom_rpms }}"
  when: gadget_pppd_custom_rpm_dir is defined

# TODO: Need a way to select required NetworkManager rpms on the fly

- name: Install custom RPMs as necessary
  yum:
    name: "{{ gadget_pppd_custom_rpm_dir | default(gadget_pppd_custom_rpm_uri) }}/{{ item }}"
    state: present
  with_items: "{{ gadget_pppd_custom_rpms }}"

- include: default-packges.yml
