---
- name: Add custom rpm dir
  become: yes
  file:
    path: "{{ gadget_pppd_custom_rpm_dir }}"
    state: directory
  when: not gadget_pppd_skip_custom_rpms|default(false)

- name: Copy custom RPMs
  become: yes
  copy:
    src: "{{ gadget_pppd_custom_rpm_dir_src }}/{{ item }}"
    dest: "{{ gadget_pppd_custom_rpm_dir }}"
  with_items: "{{ gadget_pppd_custom_rpms }}"
  when: not gadget_pppd_skip_custom_rpms|default(false)

# TODO: Need a way to select required NetworkManager rpms on the fly

- name: Install custom RPMs as necessary
  become: yes
  yum:
    name: "{{ gadget_pppd_custom_rpm_dir | default(gadget_pppd_custom_rpm_uri) }}/{{ item }}"
    state: present
  with_items: "{{ gadget_pppd_custom_rpms }}"
  when: not gadget_pppd_skip_custom_rpms|default(false)

- include: default-packages.yml
