---
- name: Add custom rpm dir
  become: yes
  file:
    path: "{{ gadget_pppd_custom_rpm_dir }}"
    state: directory
  when: gadget_pppd_custom_rpm_dir is not none

- name: Copy custom RPMs
  become: yes
  copy:
    src: "{{ gadget_pppd_custom_rpm_dir_src }}/{{ item }}"
    dest: "{{ gadget_pppd_custom_rpm_dir }}"
  with_items: "{{ gadget_pppd_custom_rpms }}"
  when: gadget_pppd_custom_rpm_dir is not none

# TODO: Need a way to select required NetworkManager rpms on the fly

- name: Install custom RPMs as necessary
  become: yes
  yum:
    name: "{{ gadget_pppd_custom_rpm_dir | default(gadget_pppd_custom_rpm_uri) }}/{{ item }}"
    state: present
  with_items: "{{ gadget_pppd_custom_rpms }}"
  when: gadget_pppd_custom_rpm_dir is not none

- include: default-packages.yml
